# File: .github/workflows/pages.yml
name: Deploy GitHub Pages with LFS - version 2

on:
  push:
    branches: [ master ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo with LFS
        uses: actions/checkout@v3
        with:
          lfs: true

      - name: Setup GitHub Pages
        uses: actions/configure-pages@v4

      - name: Upload site content
        uses: actions/upload-pages-artifact@v2
        with:
          path: '.'

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v2
