name: Deploy to GitHub Pages

on:
  push:
    branches: [ master ]  # change if your branch is named differently
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository (with LFS)
        uses: actions/checkout@v3
        with:
          lfs: true

      - name: Fetch Git LFS files
        run: git lfs pull

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: '.'  # or the path to your site files

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v2
