name: Deploy GitHub Pages with LFS

on:
  push:
    branches: [ master ]  # Or 'master' if that’s your default branch
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository (with LFS)
        uses: actions/checkout@v3
        with:
          lfs: true

      - name: Set up GitHub Pages
        uses: actions/configure-pages@v4

      - name: Upload GitHub Pages artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: '.'  # Change this if your site is in a subfolder like "build" or "dist"

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v2
